title: notetaker
description: Obsidian notes published via GitHub Pages

# Project Pages (https://<user>.github.io/<repo>/)
url: "https://alfajr666.github.io"
baseurl: "/notetaker"

remote_theme: amitmerchant1990/reverie

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-paginate

paginate: 20
paginate_path: "/page:num/"
